export const GETDRINKSBYCATEGORYSAGA = 'GETDRINKSBYCATEGORYSAGA';
export const GETDRINKSBYCATEGORY = 'GETDRINKSBYCATEGORY';

export const GETDRINKBYIDSAGA = 'GETDRINKBYIDSAGA';
export const GETDRINKBYID = 'GETDRINKBYID';

export const SEARCHDRINKSSAGA = 'SEARCHDRINKSSAGA';
export const SEARCHDRINKS = 'SEARCHDRINKS';
